ext {
    capacitorCompileSdk = project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 34
    capacitorMinSdk = project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 22
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
    }
}

apply plugin: 'com.android.library'

android {
    namespace "com.appnfc.nfcnative"
    compileSdk capacitorCompileSdk

    defaultConfig {
        minSdk capacitorMinSdk
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lintOptions {
        abortOnError false
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(':capacitor-android')
}
